steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/d01-playground/monsters-rolodex/monster-rolodex', '.', '-f', 'Dockerfile']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/d01-playground/monsters-rolodex/monster-rolodex']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'monster-rolodex', '--image', 'gcr.io/d01-playground/monsters-rolodex/monster-rolodex', '--region', 'europe-west3']
images:
- gcr.io/d01-playground/monsters-rolodex/monster-rolodex
